url: https://tenet-rccpii.github.io/BlendedLearningSIG-JHB-2018/
baseurl: "/"

# Site settings
title: Blended Learning SIG Meeting - Johannesburg 2018 
email: sa-blended-learning-sig@googlegroups.com
description: "The official website for the Blended Learning SIG Meeting -Johannesburg 2018"



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: https://twitter.com/
#  - title: github
#    url: https://github.com/carpentries/
#  - title: facebook
#    url: https://www.facebook.com/carpentries/
#  - title: slack
#    url: https://swc-slack-invite.herokuapp.com/

# Postal address (add as many lines as necessary)
#address:
#  - line: Brisbane, Australia

# Build settings
markdown: kramdown
permalink: pretty
